CREATE OR REPLACE TRIGGER TRG_PEDIDO
    BEFORE INSERT ON TB_PEDIDO
    FOR EACH ROW
BEGIN
    IF :NEW.STATUS IS NULL THEN
        :NEW.STATUS := 'NOVO PEDIDO';
    END IF;
END;

INSERT INTO TB_PEDIDO VALUES (1, SYSDATE, 'TV', 'PROCESSADO');
COMMIT;
